import {InventoryDashboard} from './inventory-dashboard';
import {Component,ChangeDetectionStrategy,HostListener,provideZoneChangeDetection} from '@angular/core';import {CommonModule} from '@angular/common';import {FormsModule} from '@angular/forms';
@Component({selector:'app-root',standalone:true,imports:[CommonModule,FormsModule,InventoryDashboard],changeDetection:ChangeDetectionStrategy.Eager,templateUrl:'./shop.html'})
export class Shop {model:any={};session:any={};form:any={};message='';loading=false;menu=false;image:File|undefined;route=location.pathname+location.search;ready:Promise<any>;
constructor(){this.ready=this.load(this.route);}@HostListener('window:popstate') pop(){this.load(location.pathname+location.search);}
async load(route:string){this.route=route;this.loading=true;this.message='';this.menu=false;try{this.session=await fetch('/api/session').then(r=>r.json());const r=await fetch('/api'+route);const d=await r.json();if(d.redirect)return this.navigate(d.redirect);if(r.status===401){await this.navigate('/login');this.message='Please log in to continue.';return;}this.model=d;if(!r.ok)this.message=d.error||d.errorMessage||'Unable to load page';this.form=d.product?{...d.product}:{sku:'',category:'',quantity:'',reorderLevel:5};document.title=(d.pageTitle||'Shop')+' — Risa';}catch(e){this.message='Unable to reach the local API';}finally{this.loading=false;}}
navigate(route:string){history.pushState({},'',route);return this.load(route);}link(e:Event,route:string){e.preventDefault();this.navigate(route);}
async post(route:string,body:any={},method='POST'){this.message='';const headers:any={'x-csrf-token':this.session.csrfToken};if(!(body instanceof FormData))headers['Content-Type']='application/json';try{const r=await fetch('/api'+route,{method,headers,body:body instanceof FormData?body:JSON.stringify(body)});const d=await r.json();if(!r.ok){this.message=d.errorMessage||d.error||'Request failed';return;}if(d.redirect)await this.navigate(d.redirect);else await this.load(this.route);}catch(e){this.message='Unable to reach the local API';}}
upload(e:Event){this.image=(e.target as HTMLInputElement).files?.[0];}saveProduct(){const data=new FormData();for(const k of ['title','price','description','sku','category','quantity','reorderLevel'])data.set(k,this.form[k] == null ? '' : String(this.form[k]));if(this.model.product?._id)data.set('productId',this.model.product._id);if(this.image)data.set('image',this.image);this.post('/admin/'+(this.model.editing?'edit-product':'add-product'),data);this.image=undefined;}
deleteProduct(id:string){if(confirm('Delete this product from Risa?'))this.post('/admin/product/'+id,{},'DELETE');}
get total(){return(this.model.products||[]).reduce((n:number,x:any)=>n+x.quantity*(x.productId?.price||0),0);}}
